### ISSUE TITLE
mybee support high availability or not yet

### ISSUE THREAD

**Issue by ericxin1982** [myb-project/guide#3]
Hi all,

Sorry to ask since I have no where to reach what I am curious.
I am asking whether mybee supports high availability or cluster mode, that means I can have multiple hosts to run all VMs and they can moving from one to another without offline.

Thanks
Eric Xin

**Comment by olevole** [comment]
Hi. At the moment MyB is a standalone solution. Nevertheless, plans for the development of multinode capabilities are quite large (there is already broker support for distributed nodes).

**Comment by ericxin1982** [comment]
Thanks.
